import { z } from 'zod'

export const createObligationSchema = z.object({
  title: z.string().min(1).max(500),
  description: z.string().optional(),
  category: z.enum([
    'tax',
    'investor',
    'equity',
    'state',
    'federal',
    'contract',
    'insurance',
    'benefits',
    'governance',
    'vendor',
  ]),
  subcategory: z.string().optional(),
  frequency: z.enum(['annual', 'quarterly', 'monthly', 'weekly', 'one-time', 'event-triggered']),
  nextDueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Must be YYYY-MM-DD format'),
  lastCompletedDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
  owner: z.string().min(1),
  assignee: z.string().optional().nullable(),
  riskLevel: z.enum(['critical', 'high', 'medium', 'low']).default('medium'),
  alertDays: z.array(z.number()).optional().default([]),
  sourceDocument: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  entity: z.string().default('Acme Corp'),
  jurisdiction: z.string().optional().nullable(),
  amount: z.number().optional().nullable(),
  autoRecur: z.boolean().optional().default(false),
})

export const updateObligationSchema = z.object({
  title: z.string().min(1).max(500).optional(),
  description: z.string().optional().nullable(),
  category: z.enum([
    'tax',
    'investor',
    'equity',
    'state',
    'federal',
    'contract',
    'insurance',
    'benefits',
    'governance',
    'vendor',
  ]).optional(),
  subcategory: z.string().optional().nullable(),
  frequency: z.enum(['annual', 'quarterly', 'monthly', 'weekly', 'one-time', 'event-triggered']).optional(),
  nextDueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Must be YYYY-MM-DD format').optional(),
  lastCompletedDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
  owner: z.string().min(1).optional(),
  assignee: z.string().optional().nullable(),
  riskLevel: z.enum(['critical', 'high', 'medium', 'low']).optional(),
  alertDays: z.array(z.number()).optional(),
  sourceDocument: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  entity: z.string().optional(),
  jurisdiction: z.string().optional().nullable(),
  amount: z.number().optional().nullable(),
  autoRecur: z.boolean().optional(),
})

export const completeObligationSchema = z.object({
  completedDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Must be YYYY-MM-DD format'),
  completedBy: z.string().min(1),
  evidenceUrl: z.string().url().optional().or(z.literal('')).nullable(),
  notes: z.string().optional().nullable(),
})
